PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


SELECT ?label
WHERE {
  ?compose rdfs:label ?label.
  ?compose prov:atLocation ?location.
  ?compose prov:wasAssociatedWith ?contributor.
  ?contributor prov:atLocation ?location2.
}